/**
 * 渠道预设数据
 *
 * 新增渠道只需在此文件添加一条记录，无需修改其他代码。
 * 数据结构 key → ChannelPreset（不含 key，key 为 Record 的键名）
 */

import type { ChannelPreset } from './channel-presets'

export const CHANNEL_PRESETS_DATA: Record<string, ChannelPreset> = {
  feishu: {
    name: '飞书',
    group: 'domestic',
    color: '#3370FF',
    initials: 'FS',
    tagline: '企业级协作平台',
    docsUrl: 'https://open.feishu.cn/document/home/index',
    fields: [
      {
        key: 'appId',
        label: 'App ID',
        type: 'text',
        required: true,
        placeholder: 'cli_xxxxxxxxxxxxxxxx',
        apiKeyUrl: 'https://open.feishu.cn/app',
        helpText: '飞书开放平台应用的 App ID',
      },
      {
        key: 'appSecret',
        label: 'App Secret',
        type: 'password',
        required: true,
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        helpText: '飞书开放平台应用的 App Secret',
      },
      {
        key: 'domain',
        label: 'Domain',
        type: 'select',
        required: true,
        placeholder: '选择飞书域名',
        options: [
          { label: '中国大陆（feishu）', value: 'feishu' },
          { label: '国际版（lark）', value: 'lark' },
        ],
        helpText: '默认使用 feishu（中国大陆）；国际版请切换到 lark',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['allowlist', 'open', 'disabled'],
  },

  wecom: {
    name: '企业微信',
    group: 'domestic',
    color: '#07C160',
    initials: 'WC',
    tagline: '腾讯企业通讯平台',
    docsUrl: 'https://developer.work.weixin.qq.com/document/path/90594',
    fields: [
      {
        key: 'botId',
        label: 'Bot ID',
        type: 'text',
        required: true,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        apiKeyUrl: 'https://developer.work.weixin.qq.com/',
        helpText: '企业微信 AI Bot 的 Bot ID',
      },
      {
        key: 'secret',
        label: 'Secret',
        type: 'password',
        required: true,
        placeholder: '企业微信 Bot Secret',
        helpText: '企业微信 AI Bot 的 Secret',
      },
    ],
    dmPolicies: ['pairing', 'allowlist', 'disabled'],
    supportsGroup: false,
    groupPolicies: [],
  },
  'openclaw-weixin': {
    name: '微信',
    group: 'domestic',
    color: '#07C160',
    initials: 'WX',
    tagline: '扫码连接个人微信',
    docsUrl: 'https://www.npmjs.com/package/@tencent-weixin/openclaw-weixin',
    fields: [],
    dmPolicies: ['pairing', 'allowlist', 'open', 'disabled'],
    supportsGroup: false,
    groupPolicies: [],
  },
  qqbot: {
    name: 'QQ Bot',
    group: 'domestic',
    color: '#1677FF',
    initials: 'QQ',
    tagline: '腾讯 QQ 机器人平台',
    docsUrl: 'https://q.qq.com/qqbot/openclaw/',
    fields: [
      {
        key: 'appId',
        label: 'App ID',
        type: 'text',
        required: true,
        placeholder: '12345678',
        apiKeyUrl: 'https://q.qq.com/qqbot/openclaw/',
        helpText: 'QQ 开放平台机器人 App ID',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
        placeholder: 'QQ Bot Client Secret',
        helpText: 'QQ 开放平台机器人 Client Secret',
      },
    ],
    dmPolicies: ['open', 'allowlist', 'pairing', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  'dingtalk-connector': {
    name: '钉钉',
    group: 'domestic',
    color: '#1677FF',
    initials: 'DD',
    tagline: '阿里企业协作平台',
    docsUrl: 'https://www.npmjs.com/package/@dingtalk-real-ai/dingtalk-connector',
    fields: [
      {
        key: 'clientId',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'dingxxxxxxxxxxxxxxxx',
        apiKeyUrl: 'https://open-dev.dingtalk.com/',
        helpText: '钉钉开放平台应用的 Client ID',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
        placeholder: '钉钉应用 Client Secret',
        helpText: '钉钉开放平台应用的 Client Secret',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  telegram: {
    name: 'Telegram',
    group: 'international',
    color: '#229ED9',
    initials: 'TG',
    tagline: 'Secure messaging platform',
    docsUrl: 'https://core.telegram.org/bots',
    fields: [
      {
        key: 'botToken',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: '123456789:ABCdefGHIjklMNO...',
        apiKeyUrl: 'https://t.me/BotFather',
        helpText: '通过 @BotFather 创建机器人后获取的 Token',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  discord: {
    name: 'Discord',
    group: 'international',
    color: '#5865F2',
    initials: 'DC',
    tagline: 'Community & gaming chat',
    docsUrl: 'https://discord.com/developers/docs/intro',
    fields: [
      {
        key: 'token',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: 'MTxxxxxxxxxxxxxxxxxxxxxxxx.Gxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        apiKeyUrl: 'https://discord.com/developers/applications',
        helpText: '在 Discord Developer Portal 创建 Bot 后获取的 Token',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  slack: {
    name: 'Slack',
    group: 'international',
    color: '#4A154B',
    initials: 'SK',
    tagline: 'Team collaboration workspace',
    docsUrl: 'https://docs.openclaw.ai/channels/slack',
    fields: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'select',
        required: true,
        placeholder: '选择接入模式',
        options: [
          { label: 'Socket Mode', value: 'socket' },
          { label: 'HTTP Events API', value: 'http' },
        ],
        helpText: 'MVP 默认建议使用 Socket Mode；HTTP Events API 需要额外配置公网回调。',
      },
      {
        key: 'botToken',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: 'xoxb-xxxxxxxxxxxxxxxx',
        apiKeyUrl: 'https://api.slack.com/apps',
        helpText: 'Slack Bot User OAuth Token（通常以 xoxb- 开头）',
      },
      {
        key: 'appToken',
        label: 'App Token',
        type: 'password',
        required: false,
        placeholder: 'xapp-xxxxxxxxxxxxxxxx',
        helpText: 'Socket Mode 必填；通常以 xapp- 开头',
      },
      {
        key: 'signingSecret',
        label: 'Signing Secret',
        type: 'password',
        required: false,
        placeholder: 'Slack Signing Secret',
        helpText: 'HTTP Events API 模式使用',
      },
      {
        key: 'webhookPath',
        label: 'Webhook Path',
        type: 'text',
        required: false,
        placeholder: '/channels/slack/events',
        helpText: 'HTTP Events API 模式使用；需与网关路由保持一致',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  whatsapp: {
    name: 'WhatsApp',
    group: 'international',
    color: '#25D366',
    initials: 'WA',
    tagline: 'Meta messaging platform',
    docsUrl: 'https://docs.openclaw.ai/channels/whatsapp',
    fields: [],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },

  bluebubbles: {
    name: 'BlueBubbles',
    group: 'international',
    color: '#4C8BF5',
    initials: 'BB',
    tagline: 'Recommended iMessage bridge',
    docsUrl: 'https://docs.openclaw.ai/channels/bluebubbles',
    fields: [
      {
        key: 'serverUrl',
        label: 'Server URL',
        type: 'text',
        required: true,
        placeholder: 'http://192.168.1.100:1234',
        helpText: 'BlueBubbles Server 的 HTTP 地址',
      },
      {
        key: 'password',
        label: 'Password',
        type: 'password',
        required: true,
        placeholder: 'BlueBubbles API password',
        helpText: 'BlueBubbles Server Web API 密码',
      },
      {
        key: 'webhookPath',
        label: 'Webhook Path',
        type: 'text',
        required: false,
        placeholder: '/bluebubbles-webhook',
        helpText: '可选。Webhook 路径；留空时可使用 OpenClaw 默认值。',
      },
    ],
    dmPolicies: ['pairing', 'open', 'allowlist', 'disabled'],
    supportsGroup: true,
    groupPolicies: ['open', 'allowlist', 'disabled'],
  },
}
